FROM jupyter/base-notebook

USER root

# Install all OS dependencies for fully functional notebook server
RUN wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb \
    && sudo dpkg -i packages-microsoft-prod.deb \
    && apt-get update && apt-get install -yq --no-install-recommends \
    build-essential \
    emacs \
    git \
    inkscape \
    jed \
    libsm6 \
    libxext-dev \
    libxrender1 \
    lmodern \
    netcat \
    pandoc \
    python-dev \
    texlive-fonts-extra \
    texlive-fonts-recommended \
    texlive-generic-recommended \
    texlive-latex-base \
    texlive-latex-extra \
    texlive-xetex \
    tzdata \
    unzip \
    nano \
    ca-certificates \
    powershell \
    azure-cli \
    && apt-get autoremove -y \
    && apt-get clean \
    && update-ca-certificates \
    && rm -rf /var/lib/apt/lists/* /var/tmp/* /tmp/* packages-microsoft-prod.deb

RUN pip install bash_kernel \
    && python -m bash_kernel.install

#RUN pip install powershell_kernel \
#    python -m powershell_kernel.install

RUN az extension add --name azure-devops \
    && az extension add --name subscription \
    && az extension add --name resource-graph \
    && az extension add --name webapp \
    && az extension add --name privatedns \
    && az extension add --name peering \
    && az extension add --name managementgroups \
    && az extension add --name log-analytics

USER $NB_UID