FROM ubuntu:latest

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    git bash wget unzip ca-certificates \
    && apt-get autoremove -y \
    && apt-get clean \
    && update-ca-certificates \
    && rm -rf /var/lib/apt/lists/* /var/tmp/* /tmp/*

ENV TERRAFORM_VERSION=0.12.7
ENV TERRAFORM_SHA256SUM=a0fa11217325f76bf1b4f53b0f7a6efb1be1826826ef8024f2f45e60187925e7

ADD https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip ./
ADD https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_SHA256SUMS ./

RUN sed -i "/terraform_${TERRAFORM_VERSION}_linux_amd64.zip/!d" "terraform_${TERRAFORM_VERSION}_SHA256SUMS"
RUN sha256sum -c terraform_${TERRAFORM_VERSION}_SHA256SUMS
RUN unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/local/bin
RUN rm -f terraform_${TERRAFORM_VERSION}_linux_amd64.zip