FROM ubuntu:18.04

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    git bash wget unzip jq ca-certificates \
    && update-ca-certificates

RUN wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
    powershell \
    && pwsh -c "Set-PSRepository -Name PSGallery -InstallationPolicy Trusted" \
    && pwsh -c "Install-Module -Name az -Force -Scope AllUsers" \
    && pwsh -c "Install-Module -Name Pester -Force -Scope AllUsers" \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /var/tmp/* /tmp/*

ENV TERRAFORM_VERSION=0.12.28
ENV TERRAFORM_SHA256SUM=be99da1439a60942b8d23f63eba1ea05ff42160744116e84f46fc24f1a8011b6

ADD https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip ./
ADD https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_SHA256SUMS ./

RUN sed -i "/terraform_${TERRAFORM_VERSION}_linux_amd64.zip/!d" "terraform_${TERRAFORM_VERSION}_SHA256SUMS"
RUN sha256sum -c terraform_${TERRAFORM_VERSION}_SHA256SUMS
RUN unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/local/bin
RUN rm -f terraform_${TERRAFORM_VERSION}_linux_amd64.zip
RUN rm -f packages-microsoft-prod.deb