FROM ubuntu:latest

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    git bash wget unzip ca-certificates \
    && apt-get autoremove -y \
    && apt-get clean \
    && update-ca-certificates \
    && rm -rf /var/lib/apt/lists/* /var/tmp/* /tmp/*

ENV TERRAFORM_VERSION=0.12.12
ENV TERRAFORM_SHA256SUM=67bc7a49c0946ad48b14cc6e95482fdd3e7e9f7dc6811f4ce6ff531fc565bd3a

ADD https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip ./
ADD https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_SHA256SUMS ./

RUN sed -i "/terraform_${TERRAFORM_VERSION}_linux_amd64.zip/!d" "terraform_${TERRAFORM_VERSION}_SHA256SUMS"
RUN sha256sum -c terraform_${TERRAFORM_VERSION}_SHA256SUMS
RUN unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/local/bin
RUN rm -f terraform_${TERRAFORM_VERSION}_linux_amd64.zip